# *************************************
# .travis.yml - Travis CI configuration
# *************************************
#
# Otherwise, we get errors. See https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments.
sudo: required
addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
      - xvfb

# See https://docs.travis-ci.com/user/multi-os/.
os: linux
# See https://docs.travis-ci.com/user/languages/python.
language: python
# We only support Python 3.5+ (where there are qtpy wheels available).
python:
  - 3.5
  - 3.6
  - 3.7

# See https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix. This
# manually includes additional OS X tests to the matrix of Linux tests defined
# above.
matrix:
  include:
  - os: osx
    # Since Travis's OS X doesn't natively support Python, use some workarounds.
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.5.6 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.6.6 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.7.0 VENV=venv

# Travis complains if tests are run during install, or if installation is done
# during script (the tests). So, break the script into two pieces.
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tests/ci/linux_install.sh; fi
  # source used on MacOS to preserve python venv
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source tests/ci/osx_install.sh; fi
  - python -m pip install -e .

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi

script:
  # Source virtualenv on OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/test_tools.sh; fi
  # Set display on Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - "cd tests"
  - "python3 run_all.py"

cache:
  directories:
    - /downloads
  apt: true

