# *************************************
# .travis.yml - Travis CI configuration
# *************************************
# See https://docs.travis-ci.com/user/languages/python.

# We only support Python 3.
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# Based on https://github.com/harvimt/quamash/blob/master/.travis.yml
# From here...
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Cached Downloads
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - if [ ! -f /downloads/sip.tar.gz ];   then curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz; fi
  - if [ ! -f /downloads/pyqt5.tar.gz ]; then curl -L -o /downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4/PyQt-gpl-5.4.tar.gz; fi
  - echo '6d01ea966a53e4c7ae5c5e48c40e49e5  /downloads/sip.tar.gz' | md5sum -c -
  - echo '7f2eb79eaf3d7e5e7df5a4e9c8c9340e  /downloads/pyqt5.tar.gz' | md5sum -c -
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
install:
  # Qt5
  - sudo add-apt-repository -y ppa:beineri/opt-qt542
  - sudo apt-get update
  - sudo apt-get install -y qt54base
  # Builds
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt5
  - source /opt/qt54/bin/qt54-env.sh  # switch to Qt5
  - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
  - pushd PyQt-gpl-5.4
  - python configure.py -c --confirm-license --no-designer-plugin
  - make
  - sudo make install
  - popd
  # Builds Complete
  - popd

cache:
  directories:
    - /downloads
  apt: true
# ... to here.

# Run the tests.
script:
  - python setup.py install
  - cd tests
  - python run_all.py
