######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 4 19:08:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
